services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: h_simulador_api:latest
    container_name: h_simulador_api
    environment:
      - DATA_DIR=/data
      - CORS_ORIGINS=*
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"     # ← publica 8000 al host
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:8000/healthz').status==200 else 1)"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
